apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "maildev.fullname" . }}-relay-rules
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
data:
  auto-relay-rules.json: "[\n\t{ \"allow\": \"*\" }\n]\n"
