{{- if .Values.ports.smtp }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "maildev.fullname" . }}-smtp
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: smtp-{{ .Values.ports.smtp }}-tcp
      port: {{ .Values.ports.smtp }}
      protocol: TCP
      targetPort: {{ .Values.ports.smtp }}
  selector:
    {{- include "maildev.selectorLabels" . | nindent 4 }}
{{- end }}
